# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.4
  - 5.5

env:
  - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.3
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.4
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.5 SUBSITES=1
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - "if [ \"$SUBSITES\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
  - "if [ \"$SUBSITES\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/subsites; fi"
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit secureassets/tests
